import { getServerSession } from "next-auth";
import ProviderSession from "./providers/ProviderSession";
import { Metadata } from "next";
import "./globals.css";
import { authOptions } from "./lib/auth";

// Metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout to wrap the app with session context
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Get session from the server
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <ProviderSession session={session}>
          {children}
        </ProviderSession>
      </body>
    </html>
  );
}
